'use strict';

/**
 * SuiteRunner - Orchestrates multiple test types from validated JSON suite manifests
 *
 * Supports:
 * - Schema validation via ajv
 * - Tag filtering for selective test execution
 * - Suite-level timeout enforcement
 * - Result aggregation with pass/fail/skip counts
 * - History logging to history.jsonl
 */

const Ajv = require('ajv');
const addFormats = require('ajv-formats');
const fs = require('fs');
const path = require('path');

// Test modules
const { loginHomeBay, registerHomeBay } = require('../homebay/auth');
const { auditHomeBayRole } = require('../homebay/performance');
const { captureHomeBayRole, compareAgainstBaseline } = require('../homebay/visual');
const { testHomeBayAnimations } = require('../homebay/animationTest');
const { auditHomeBayRole: auditAccessibility } = require('../homebay/accessibility');
const { DryRunTester } = require('../homebay/dryrun');

const SUITES_REPORTS_DIR = path.join(__dirname, '../../reports/suites');
const SCHEMA_PATH = path.join(__dirname, '../../config/suites/suite.schema.json');

class SuiteRunner {
  constructor(suite, options = {}) {
    // Validate suite against schema (SUITE-01 requirement)
    this._validateSchema(suite);

    this.suite = suite;           // Parsed suite manifest JSON
    this.runId = options.runId;   // ISO timestamp from API route
    this.tags = options.tags || []; // Tag filter array
    this.dryRun = options.dryRun || false;
    this.results = [];            // Per-test results array
    this.startTime = null;
    this.endTime = null;
  }

  /**
   * Static method to replay a historical run
   * Loads suite config from historical summary.json and re-executes with new runId
   * @param {string} suiteId - Suite identifier
   * @param {string} runId - Historical run identifier
   * @param {string} [newRunId] - New run identifier (generated by caller if omitted)
   * @returns {Promise<Object>} New run results with new runId
   */
  static async replayRun(suiteId, runId, newRunId) {
    // Validate IDs to prevent path traversal
    const { safeId, safePath } = require('../utils/safePath');
    safeId(suiteId);
    safeId(runId);

    // Load historical summary to get original suite config
    const summaryPath = safePath(SUITES_REPORTS_DIR, suiteId, runId, 'summary.json');
    if (!fs.existsSync(summaryPath)) {
      throw new Error('Historical run not found');
    }

    // Check file size before reading (prevent OOM)
    const stats = await fs.promises.stat(summaryPath);
    const MAX_SUMMARY_SIZE = 10 * 1024 * 1024; // 10MB limit
    if (stats.size > MAX_SUMMARY_SIZE) {
      throw new Error(`Summary file too large (${Math.round(stats.size / 1024 / 1024)}MB, max 10MB)`);
    }

    const summary = JSON.parse(await fs.promises.readFile(summaryPath, 'utf8'));

    // Check if summary has suite config (added in Task 1)
    if (!summary.suite || !summary.originalTests) {
      throw new Error(`Historical run ${runId} is missing suite config (was it saved before Phase 12?)`);
    }

    // Reconstruct suite manifest from summary
    const suite = {
      suite: summary.suite,
      tests: summary.originalTests
    };

    // Execute with caller-provided runId to keep API/job tracking consistent
    const replayRunId = newRunId || new Date().toISOString().replace(/[:.]/g, '-');
    const runner = new SuiteRunner(suite, {
      runId: replayRunId,
      tags: summary.tags || [],  // Preserve original tag filter
      dryRun: summary.dryRun || false
    });

    console.log(`[SuiteRunner] Replaying ${suiteId}/${runId} as ${replayRunId}`);

    return await runner.execute();
  }

  /**
   * Validate suite manifest against JSON schema using ajv.
   * Throws descriptive error if validation fails.
   * @private
   */
  _validateSchema(suite) {
    // Load and compile schema
    const schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8'));
    const ajv = new Ajv();
    addFormats(ajv);
    const validate = ajv.compile(schema);

    // Validate
    const valid = validate(suite);
    if (!valid) {
      const errors = validate.errors.map(e => `${e.instancePath} ${e.message}`).join('; ');
      throw new Error(`Suite validation failed: ${errors}`);
    }
  }

  /**
   * Execute the test suite with timeout enforcement.
   * Returns aggregated results object.
   */
  async execute() {
    const timeout = this.suite.suite.timeout || 300000;

    try {
      // Wrap execution in Promise.race with suite timeout
      const result = await Promise.race([
        this._runTests(),
        new Promise((_, reject) =>
          setTimeout(() => reject(new Error(`Suite timeout after ${timeout}ms`)), timeout)
        )
      ]);

      return result;
    } catch (error) {
      // Generate error results
      const duration = this.endTime ? this.endTime - this.startTime : 0;
      const results = this._generateResults(duration, error);
      await this._saveResults(results);
      return results;
    }
  }

  /**
   * Run all tests in the suite with tag filtering and fail-fast on critical failures.
   * @private
   */
  async _runTests() {
    this.startTime = Date.now();

    for (const test of this.suite.tests) {
      // Tag filtering: skip test if tags provided and test doesn't match
      if (this.tags.length > 0) {
        const testTags = test.tags || [];
        const matchesTag = this.tags.some(t => testTags.includes(t));

        if (!matchesTag) {
          this.results.push({
            ...test,
            status: 'skipped',
            reason: 'Tag filter mismatch',
            duration: 0
          });
          continue;
        }
      }

      // Execute test
      const testStart = Date.now();
      let testResult;

      try {
        testResult = await this._executeTest(test);
        testResult.duration = Date.now() - testStart;
        testResult.status = testResult.success ? 'passed' : 'failed';
      } catch (error) {
        testResult = {
          ...test,
          status: 'failed',
          duration: Date.now() - testStart,
          error: error.message,
          stack: error.stack
        };
      }

      this.results.push(testResult);

      // Fail-fast on critical test failures
      if (test.critical && testResult.status === 'failed') {
        throw new Error(`Critical test failed: ${test.type} (${testResult.error})`);
      }
    }

    this.endTime = Date.now();
    const duration = this.endTime - this.startTime;
    const results = this._generateResults(duration, null);
    await this._saveResults(results);

    return results;
  }

  /**
   * Execute a single test by dispatching to the appropriate module based on test.type.
   * @private
   */
  async _executeTest(test) {
    const { type, role, config = {} } = test;

    switch (type) {
      case 'auth':
        // Auth test - login or register based on config.flow
        if (config.flow === 'register') {
          const result = await registerHomeBay(
            config.email || `test-${Date.now()}@example.com`,
            config.password || 'Test1234!',
            config.dateOfBirth
          );
          return { ...test, success: result.success, data: result };
        } else {
          // Default to login
          const result = await loginHomeBay(role);
          return { ...test, success: result.success, data: result };
        }

      case 'performance':
        // Performance audit - run Lighthouse audit on role's critical pages
        const perfResult = await auditHomeBayRole(role);
        return { ...test, success: true, data: perfResult };

      case 'visual':
        // Visual test - capture screenshots and optionally compare against baseline
        if (config.compare) {
          const compareResult = await compareAgainstBaseline(role);
          return {
            ...test,
            success: compareResult.matched === compareResult.totalCompared,
            data: compareResult
          };
        } else {
          const captureResult = await captureHomeBayRole(role);
          return { ...test, success: true, data: captureResult };
        }

      case 'animation':
        // Animation test - test animations on role's pages
        const animResult = await testHomeBayAnimations(role, config);
        return { ...test, success: true, data: animResult };

      case 'accessibility':
        // Accessibility audit - runs axe-core on role's critical pages
        const a11yResult = await auditAccessibility(role);
        return { ...test, success: true, data: a11yResult };

      case 'dry-run':
        // Dry-run test - validate form without submitting
        if (!config.formUrl || !config.formData) {
          throw new Error('dry-run test requires config.formUrl and config.formData');
        }

        const tester = new DryRunTester();
        const dryrunResult = await tester.testFormValidation(
          role || null,  // null for unauthenticated forms
          config.formUrl,
          config.formData,
          config.expectedErrors || []
        );

        return {
          ...test,
          success: dryrunResult.passed,
          data: dryrunResult
        };

      default:
        throw new Error(`Unknown test type: ${type}`);
    }
  }

  /**
   * Aggregate per-test results into suite summary.
   * @private
   */
  _generateResults(duration, error) {
    const total = this.results.length;
    const passed = this.results.filter(r => r.status === 'passed').length;
    const failed = this.results.filter(r => r.status === 'failed').length;
    const skipped = this.results.filter(r => r.status === 'skipped').length;

    const status = error ? 'error' : (failed > 0 ? 'failed' : 'passed');

    return {
      suiteId: this.suite.suite.id,
      suiteName: this.suite.suite.name,
      suiteVersion: this.suite.suite.version,
      runId: this.runId,
      status,
      startTime: new Date(this.startTime).toISOString(),
      endTime: this.endTime ? new Date(this.endTime).toISOString() : new Date().toISOString(),
      duration,
      summary: {
        total,
        passed,
        failed,
        skipped,
        passRate: total > 0 ? Math.round((passed / total) * 100) : 0
      },
      tests: this.results,
      error: error ? error.message : null,
      tags: this.tags,
      dryRun: this.dryRun
    };
  }

  /**
   * Save results to disk:
   * - Write to reports/suites/{suiteId}/{runId}/summary.json (includes suite config for replay)
   * - Append to reports/suites/history.jsonl
   * @private
   */
  async _saveResults(results) {
    const suiteId = this.suite.suite.id;
    const runDir = path.join(SUITES_REPORTS_DIR, suiteId, this.runId);

    // Create directory structure
    await fs.promises.mkdir(runDir, { recursive: true });

    // Write summary.json with full suite config for replay support
    const summaryPath = path.join(runDir, 'summary.json');
    const summaryWithConfig = {
      ...results,
      suite: this.suite.suite,  // Full suite metadata from manifest
      originalTests: this.suite.tests  // Original test definitions (before execution)
    };

    try {
      await fs.promises.writeFile(summaryPath, JSON.stringify(summaryWithConfig, null, 2));
    } catch (err) {
      if (err.message && err.message.includes('circular')) {
        console.error('[SuiteRunner] Circular reference detected, saving without suite config');
        // Fallback: save results without the problematic config
        await fs.promises.writeFile(summaryPath, JSON.stringify(results, null, 2));
      } else {
        throw err;
      }
    }

    // Append to history.jsonl
    const historyPath = path.join(SUITES_REPORTS_DIR, 'history.jsonl');
    const historyEntry = {
      runId: this.runId,
      suiteId,
      suiteName: results.suiteName,
      status: results.status,
      duration: results.duration,
      passRate: results.summary.passRate,
      timestamp: results.startTime,
      tags: this.tags
    };
    await fs.promises.appendFile(historyPath, JSON.stringify(historyEntry) + '\n');

    console.log(`[SuiteRunner] Results saved to ${summaryPath}`);
    console.log(`[SuiteRunner] History updated at ${historyPath}`);
  }
}

module.exports = { SuiteRunner };
